import type { KanjiItem } from "./types";

export const KANJI: KanjiItem[] = [
  { id: "kj-日", glyph: "日", meaning: "day / sun", onyomi: "にち・じつ", kunyomi: "ひ・か", level: "N5", example: "今日", exampleReading: "きょう", exampleMeaning: "today" },
  { id: "kj-月", glyph: "月", meaning: "month / moon", onyomi: "げつ・がつ", kunyomi: "つき", level: "N5", example: "来月", exampleReading: "らいげつ", exampleMeaning: "next month" },
  { id: "kj-火", glyph: "火", meaning: "fire", onyomi: "か", kunyomi: "ひ", level: "N5", example: "火曜日", exampleReading: "かようび", exampleMeaning: "Tuesday" },
  { id: "kj-水", glyph: "水", meaning: "water", onyomi: "すい", kunyomi: "みず", level: "N5", example: "水を飲む", exampleReading: "みずをのむ", exampleMeaning: "drink water" },
  { id: "kj-木", glyph: "木", meaning: "tree / wood", onyomi: "もく・ぼく", kunyomi: "き", level: "N5", example: "木曜日", exampleReading: "もくようび", exampleMeaning: "Thursday" },
  { id: "kj-金", glyph: "金", meaning: "gold / money", onyomi: "きん・こん", kunyomi: "かね", level: "N5", example: "お金", exampleReading: "おかね", exampleMeaning: "money" },
  { id: "kj-土", glyph: "土", meaning: "earth / soil", onyomi: "ど・と", kunyomi: "つち", level: "N5", example: "土曜日", exampleReading: "どようび", exampleMeaning: "Saturday" },
  { id: "kj-人", glyph: "人", meaning: "person", onyomi: "じん・にん", kunyomi: "ひと", level: "N5", example: "日本人", exampleReading: "にほんじん", exampleMeaning: "Japanese person" },
  { id: "kj-山", glyph: "山", meaning: "mountain", onyomi: "さん", kunyomi: "やま", level: "N5", example: "富士山", exampleReading: "ふじさん", exampleMeaning: "Mt. Fuji" },
  { id: "kj-川", glyph: "川", meaning: "river", onyomi: "せん", kunyomi: "かわ", level: "N5", example: "川の水", exampleReading: "かわのみず", exampleMeaning: "river water" },
  { id: "kj-口", glyph: "口", meaning: "mouth", onyomi: "こう", kunyomi: "くち", level: "N5", example: "入口", exampleReading: "いりぐち", exampleMeaning: "entrance" },
  { id: "kj-目", glyph: "目", meaning: "eye", onyomi: "もく", kunyomi: "め", level: "N5", example: "目が見える", exampleReading: "めがみえる", exampleMeaning: "can see" },
  { id: "kj-見", glyph: "見", meaning: "see / look", onyomi: "けん", kunyomi: "み", level: "N5", example: "見る", exampleReading: "みる", exampleMeaning: "to see" },
  { id: "kj-行", glyph: "行", meaning: "go", onyomi: "こう・ぎょう", kunyomi: "い・ゆ", level: "N5", example: "行く", exampleReading: "いく", exampleMeaning: "to go" },
  { id: "kj-来", glyph: "来", meaning: "come", onyomi: "らい", kunyomi: "く・き", level: "N5", example: "来る", exampleReading: "くる", exampleMeaning: "to come" },
  { id: "kj-食", glyph: "食", meaning: "eat", onyomi: "しょく", kunyomi: "た・く", level: "N5", example: "食べる", exampleReading: "たべる", exampleMeaning: "to eat" },
  { id: "kj-飲", glyph: "飲", meaning: "drink", onyomi: "いん", kunyomi: "の", level: "N5", example: "飲む", exampleReading: "のむ", exampleMeaning: "to drink" },
  { id: "kj-学", glyph: "学", meaning: "study / learn", onyomi: "がく", kunyomi: "まな", level: "N5", example: "学校", exampleReading: "がっこう", exampleMeaning: "school" },
  { id: "kj-校", glyph: "校", meaning: "school", onyomi: "こう", kunyomi: "—", level: "N5", example: "高校", exampleReading: "こうこう", exampleMeaning: "high school" },
  { id: "kj-生", glyph: "生", meaning: "life / birth", onyomi: "せい・しょう", kunyomi: "い・う・なま", level: "N5", example: "学生", exampleReading: "がくせい", exampleMeaning: "student" },
  { id: "kj-年", glyph: "年", meaning: "year", onyomi: "ねん", kunyomi: "とし", level: "N5", example: "今年", exampleReading: "ことし", exampleMeaning: "this year" },
  { id: "kj-時", glyph: "時", meaning: "time / hour", onyomi: "じ", kunyomi: "とき", level: "N5", example: "時間", exampleReading: "じかん", exampleMeaning: "time" },
  { id: "kj-間", glyph: "間", meaning: "interval / between", onyomi: "かん・けん", kunyomi: "あいだ・ま", level: "N5", example: "この間", exampleReading: "このあいだ", exampleMeaning: "the other day" },
  { id: "kj-何", glyph: "何", meaning: "what", onyomi: "か", kunyomi: "なに・なん", level: "N5", example: "何ですか", exampleReading: "なんですか", exampleMeaning: "what is it?" },
  { id: "kj-大", glyph: "大", meaning: "big", onyomi: "だい・たい", kunyomi: "おお", level: "N5", example: "大きい", exampleReading: "おおきい", exampleMeaning: "big" },
  { id: "kj-小", glyph: "小", meaning: "small", onyomi: "しょう", kunyomi: "ちい・こ", level: "N5", example: "小さい", exampleReading: "ちいさい", exampleMeaning: "small" },
  { id: "kj-中", glyph: "中", meaning: "middle / inside", onyomi: "ちゅう", kunyomi: "なか", level: "N5", example: "中国", exampleReading: "ちゅうごく", exampleMeaning: "China" },
  { id: "kj-上", glyph: "上", meaning: "up / above", onyomi: "じょう", kunyomi: "うえ・あ", level: "N5", example: "上がる", exampleReading: "あがる", exampleMeaning: "to rise" },
  { id: "kj-下", glyph: "下", meaning: "down / below", onyomi: "か・げ", kunyomi: "した・さ", level: "N5", example: "下がる", exampleReading: "さがる", exampleMeaning: "to go down" },
  { id: "kj-出", glyph: "出", meaning: "exit / put out", onyomi: "しゅつ", kunyomi: "で・だ", level: "N5", example: "出る", exampleReading: "でる", exampleMeaning: "to leave" },
  { id: "kj-入", glyph: "入", meaning: "enter", onyomi: "にゅう", kunyomi: "はい・い", level: "N5", example: "入る", exampleReading: "はいる", exampleMeaning: "to enter" },
  { id: "kj-語", glyph: "語", meaning: "language / word", onyomi: "ご", kunyomi: "かた", level: "N5", example: "日本語", exampleReading: "にほんご", exampleMeaning: "Japanese" },
  { id: "kj-本", glyph: "本", meaning: "book / origin", onyomi: "ほん", kunyomi: "もと", level: "N5", example: "日本", exampleReading: "にほん", exampleMeaning: "Japan" },
  { id: "kj-車", glyph: "車", meaning: "car / vehicle", onyomi: "しゃ", kunyomi: "くるま", level: "N5", example: "電車", exampleReading: "でんしゃ", exampleMeaning: "train" },
  { id: "kj-電", glyph: "電", meaning: "electricity", onyomi: "でん", kunyomi: "—", level: "N5", example: "電話", exampleReading: "でんわ", exampleMeaning: "telephone" },
  { id: "kj-話", glyph: "話", meaning: "talk / story", onyomi: "わ", kunyomi: "はなし・はな", level: "N5", example: "話す", exampleReading: "はなす", exampleMeaning: "to speak" },
  { id: "kj-聞", glyph: "聞", meaning: "hear / ask", onyomi: "ぶん・もん", kunyomi: "き", level: "N5", example: "聞く", exampleReading: "きく", exampleMeaning: "to listen" },
  { id: "kj-読", glyph: "読", meaning: "read", onyomi: "どく", kunyomi: "よ", level: "N5", example: "読む", exampleReading: "よむ", exampleMeaning: "to read" },
  { id: "kj-書", glyph: "書", meaning: "write", onyomi: "しょ", kunyomi: "か", level: "N5", example: "書く", exampleReading: "かく", exampleMeaning: "to write" },
  { id: "kj-買", glyph: "買", meaning: "buy", onyomi: "ばい", kunyomi: "か", level: "N5", example: "買う", exampleReading: "かう", exampleMeaning: "to buy" },
  { id: "kj-高", glyph: "高", meaning: "high / expensive", onyomi: "こう", kunyomi: "たか", level: "N5", example: "高い", exampleReading: "たかい", exampleMeaning: "expensive / tall" },
  { id: "kj-安", glyph: "安", meaning: "cheap / peaceful", onyomi: "あん", kunyomi: "やす", level: "N5", example: "安い", exampleReading: "やすい", exampleMeaning: "cheap" },
  { id: "kj-新", glyph: "新", meaning: "new", onyomi: "しん", kunyomi: "あたら・あら", level: "N5", example: "新しい", exampleReading: "あたらしい", exampleMeaning: "new" },
  { id: "kj-古", glyph: "古", meaning: "old", onyomi: "こ", kunyomi: "ふる", level: "N5", example: "古い", exampleReading: "ふるい", exampleMeaning: "old" },
  { id: "kj-多", glyph: "多", meaning: "many", onyomi: "た", kunyomi: "おお", level: "N5", example: "多い", exampleReading: "おおい", exampleMeaning: "many" },
  { id: "kj-少", glyph: "少", meaning: "few", onyomi: "しょう", kunyomi: "すく・すこ", level: "N5", example: "少ない", exampleReading: "すくない", exampleMeaning: "few" },
  { id: "kj-今", glyph: "今", meaning: "now", onyomi: "こん", kunyomi: "いま", level: "N5", example: "今日", exampleReading: "きょう", exampleMeaning: "today" },
  { id: "kj-先", glyph: "先", meaning: "ahead / previous", onyomi: "せん", kunyomi: "さき", level: "N5", example: "先生", exampleReading: "せんせい", exampleMeaning: "teacher" },
  { id: "kj-友", glyph: "友", meaning: "friend", onyomi: "ゆう", kunyomi: "とも", level: "N5", example: "友達", exampleReading: "ともだち", exampleMeaning: "friend" },
  { id: "kj-名", glyph: "名", meaning: "name", onyomi: "めい・みょう", kunyomi: "な", level: "N5", example: "名前", exampleReading: "なまえ", exampleMeaning: "name" },
  { id: "kj-仕", glyph: "仕", meaning: "serve / do", onyomi: "し", kunyomi: "つか", level: "N4", example: "仕事", exampleReading: "しごと", exampleMeaning: "job" },
  { id: "kj-事", glyph: "事", meaning: "matter / affair", onyomi: "じ", kunyomi: "こと", level: "N4", example: "用事", exampleReading: "ようじ", exampleMeaning: "errand" },
  { id: "kj-乗", glyph: "乗", meaning: "ride", onyomi: "じょう", kunyomi: "の", level: "N4", example: "乗る", exampleReading: "のる", exampleMeaning: "to ride" },
  { id: "kj-場", glyph: "場", meaning: "place", onyomi: "じょう", kunyomi: "ば", level: "N4", example: "場所", exampleReading: "ばしょ", exampleMeaning: "place" },
  { id: "kj-開", glyph: "開", meaning: "open", onyomi: "かい", kunyomi: "あ・ひら", level: "N4", example: "開ける", exampleReading: "あける", exampleMeaning: "to open" },
  { id: "kj-発", glyph: "発", meaning: "depart / emit", onyomi: "はつ", kunyomi: "—", level: "N4", example: "出発", exampleReading: "しゅっぱつ", exampleMeaning: "departure" },
  { id: "kj-使", glyph: "使", meaning: "use", onyomi: "し", kunyomi: "つか", level: "N4", example: "使う", exampleReading: "つかう", exampleMeaning: "to use" },
  { id: "kj-作", glyph: "作", meaning: "make", onyomi: "さく", kunyomi: "つく", level: "N4", example: "作る", exampleReading: "つくる", exampleMeaning: "to make" },
  { id: "kj-知", glyph: "知", meaning: "know", onyomi: "ち", kunyomi: "し", level: "N4", example: "知る", exampleReading: "しる", exampleMeaning: "to know" },
  { id: "kj-思", glyph: "思", meaning: "think", onyomi: "し", kunyomi: "おも", level: "N4", example: "思う", exampleReading: "おもう", exampleMeaning: "to think" },
  { id: "kj-考", glyph: "考", meaning: "consider", onyomi: "こう", kunyomi: "かんが", level: "N4", example: "考える", exampleReading: "かんがえる", exampleMeaning: "to think over" },
  { id: "kj-始", glyph: "始", meaning: "begin", onyomi: "し", kunyomi: "はじ", level: "N4", example: "始める", exampleReading: "はじめる", exampleMeaning: "to start" },
  { id: "kj-終", glyph: "終", meaning: "end", onyomi: "しゅう", kunyomi: "お", level: "N4", example: "終わる", exampleReading: "おわる", exampleMeaning: "to end" },
  { id: "kj-持", glyph: "持", meaning: "hold", onyomi: "じ", kunyomi: "も", level: "N4", example: "持つ", exampleReading: "もつ", exampleMeaning: "to hold" },
  { id: "kj-待", glyph: "待", meaning: "wait", onyomi: "たい", kunyomi: "ま", level: "N4", example: "待つ", exampleReading: "まつ", exampleMeaning: "to wait" },
  { id: "kj-決", glyph: "決", meaning: "decide", onyomi: "けつ", kunyomi: "き", level: "N3", example: "決める", exampleReading: "きめる", exampleMeaning: "to decide" },
  { id: "kj-経", glyph: "経", meaning: "pass / sutra", onyomi: "けい・きょう", kunyomi: "へ", level: "N3", example: "経験", exampleReading: "けいけん", exampleMeaning: "experience" },
  { id: "kj-験", glyph: "験", meaning: "test / effect", onyomi: "けん", kunyomi: "—", level: "N3", example: "試験", exampleReading: "しけん", exampleMeaning: "exam" },
  { id: "kj-確", glyph: "確", meaning: "certain", onyomi: "かく", kunyomi: "たし", level: "N3", example: "確認", exampleReading: "かくにん", exampleMeaning: "confirmation" },
  { id: "kj-認", glyph: "認", meaning: "recognize", onyomi: "にん", kunyomi: "みと", level: "N3", example: "認める", exampleReading: "みとめる", exampleMeaning: "to acknowledge" },
  { id: "kj-議", glyph: "議", meaning: "deliberation", onyomi: "ぎ", kunyomi: "—", level: "N3", example: "会議", exampleReading: "かいぎ", exampleMeaning: "meeting" },
  { id: "kj-変", glyph: "変", meaning: "change / strange", onyomi: "へん", kunyomi: "か", level: "N3", example: "変わる", exampleReading: "かわる", exampleMeaning: "to change" },
  { id: "kj-続", glyph: "続", meaning: "continue", onyomi: "ぞく", kunyomi: "つづ", level: "N3", example: "続く", exampleReading: "つづく", exampleMeaning: "to continue" },
  { id: "kj-必", glyph: "必", meaning: "certain / must", onyomi: "ひつ", kunyomi: "かなら", level: "N3", example: "必要", exampleReading: "ひつよう", exampleMeaning: "necessary" },
  { id: "kj-要", glyph: "要", meaning: "need", onyomi: "よう", kunyomi: "い・かなめ", level: "N3", example: "要する", exampleReading: "ようする", exampleMeaning: "to require" },
  { id: "kj-構", glyph: "構", meaning: "structure / care", onyomi: "こう", kunyomi: "かま", level: "N2", example: "結構", exampleReading: "けっこう", exampleMeaning: "fine / rather" },
  { id: "kj-態", glyph: "態", meaning: "condition / form", onyomi: "たい", kunyomi: "—", level: "N2", example: "状態", exampleReading: "じょうたい", exampleMeaning: "state" },
  { id: "kj-勢", glyph: "勢", meaning: "force / momentum", onyomi: "せい", kunyomi: "いきお", level: "N2", example: "勢い", exampleReading: "いきおい", exampleMeaning: "momentum" },
  { id: "kj-従", glyph: "従", meaning: "obey / follow", onyomi: "じゅう", kunyomi: "したが", level: "N2", example: "従う", exampleReading: "したがう", exampleMeaning: "to follow" },
  { id: "kj-達", glyph: "達", meaning: "attain / plural", onyomi: "たつ", kunyomi: "—", level: "N2", example: "達成", exampleReading: "たっせい", exampleMeaning: "achievement" },
  { id: "kj-成", glyph: "成", meaning: "become / form", onyomi: "せい", kunyomi: "な", level: "N2", example: "成功", exampleReading: "せいこう", exampleMeaning: "success" },
  { id: "kj-優", glyph: "優", meaning: "gentle / superior", onyomi: "ゆう", kunyomi: "やさ・すぐ", level: "N2", example: "優先", exampleReading: "ゆうせん", exampleMeaning: "priority" },
  { id: "kj-提", glyph: "提", meaning: "propose / carry", onyomi: "てい", kunyomi: "さ", level: "N2", example: "提案", exampleReading: "ていあん", exampleMeaning: "proposal" },
  { id: "kj-円", glyph: "円", meaning: "yen / circle", onyomi: "えん", kunyomi: "まる", level: "N5", example: "百円", exampleReading: "ひゃくえん", exampleMeaning: "100 yen" },
  { id: "kj-分", glyph: "分", meaning: "minute / part", onyomi: "ふん・ぶん", kunyomi: "わ", level: "N5", example: "五分", exampleReading: "ごふん", exampleMeaning: "five minutes" },
  { id: "kj-前", glyph: "前", meaning: "before / front", onyomi: "ぜん", kunyomi: "まえ", level: "N5", example: "名前", exampleReading: "なまえ", exampleMeaning: "name" },
  { id: "kj-後", glyph: "後", meaning: "after / behind", onyomi: "ご・こう", kunyomi: "あと・うし", level: "N5", example: "午後", exampleReading: "ごご", exampleMeaning: "afternoon" },
  { id: "kj-右", glyph: "右", meaning: "right", onyomi: "う・ゆう", kunyomi: "みぎ", level: "N5", example: "右へ", exampleReading: "みぎへ", exampleMeaning: "to the right" },
  { id: "kj-左", glyph: "左", meaning: "left", onyomi: "さ", kunyomi: "ひだり", level: "N5", example: "左へ", exampleReading: "ひだりへ", exampleMeaning: "to the left" },
  { id: "kj-東", glyph: "東", meaning: "east", onyomi: "とう", kunyomi: "ひがし", level: "N5", example: "東京", exampleReading: "とうきょう", exampleMeaning: "Tokyo" },
  { id: "kj-西", glyph: "西", meaning: "west", onyomi: "せい・さい", kunyomi: "にし", level: "N5", example: "西口", exampleReading: "にしぐち", exampleMeaning: "west exit" },
  { id: "kj-南", glyph: "南", meaning: "south", onyomi: "なん", kunyomi: "みなみ", level: "N5", example: "南口", exampleReading: "みなみぐち", exampleMeaning: "south exit" },
  { id: "kj-北", glyph: "北", meaning: "north", onyomi: "ほく", kunyomi: "きた", level: "N5", example: "北海道", exampleReading: "ほっかいどう", exampleMeaning: "Hokkaido" },
  { id: "kj-外", glyph: "外", meaning: "outside", onyomi: "がい", kunyomi: "そと・はず", level: "N5", example: "外国", exampleReading: "がいこく", exampleMeaning: "foreign country" },
  { id: "kj-国", glyph: "国", meaning: "country", onyomi: "こく", kunyomi: "くに", level: "N5", example: "中国", exampleReading: "ちゅうごく", exampleMeaning: "China" },
  { id: "kj-雨", glyph: "雨", meaning: "rain", onyomi: "う", kunyomi: "あめ", level: "N5", example: "雨が降る", exampleReading: "あめがふる", exampleMeaning: "it rains" },
  { id: "kj-天", glyph: "天", meaning: "heaven / sky", onyomi: "てん", kunyomi: "あま", level: "N5", example: "天気", exampleReading: "てんき", exampleMeaning: "weather" },
  { id: "kj-気", glyph: "気", meaning: "spirit / mood", onyomi: "き・け", kunyomi: "—", level: "N5", example: "元気", exampleReading: "げんき", exampleMeaning: "healthy / well" },
  { id: "kj-休", glyph: "休", meaning: "rest", onyomi: "きゅう", kunyomi: "やす", level: "N5", example: "休む", exampleReading: "やすむ", exampleMeaning: "to rest" },
  { id: "kj-毎", glyph: "毎", meaning: "every", onyomi: "まい", kunyomi: "—", level: "N5", example: "毎日", exampleReading: "まいにち", exampleMeaning: "every day" },
  { id: "kj-週", glyph: "週", meaning: "week", onyomi: "しゅう", kunyomi: "—", level: "N5", example: "来週", exampleReading: "らいしゅう", exampleMeaning: "next week" },
  { id: "kj-曜", glyph: "曜", meaning: "day of week", onyomi: "よう", kunyomi: "—", level: "N5", example: "月曜日", exampleReading: "げつようび", exampleMeaning: "Monday" },
  { id: "kj-父", glyph: "父", meaning: "father", onyomi: "ふ", kunyomi: "ちち", level: "N5", example: "お父さん", exampleReading: "おとうさん", exampleMeaning: "father" },
  { id: "kj-母", glyph: "母", meaning: "mother", onyomi: "ぼ", kunyomi: "はは", level: "N5", example: "お母さん", exampleReading: "おかあさん", exampleMeaning: "mother" },
  { id: "kj-男", glyph: "男", meaning: "man", onyomi: "だん・なん", kunyomi: "おとこ", level: "N5", example: "男の人", exampleReading: "おとこのひと", exampleMeaning: "man" },
  { id: "kj-女", glyph: "女", meaning: "woman", onyomi: "じょ・にょ", kunyomi: "おんな", level: "N5", example: "女の人", exampleReading: "おんなのひと", exampleMeaning: "woman" },
  { id: "kj-子", glyph: "子", meaning: "child", onyomi: "し・す", kunyomi: "こ", level: "N5", example: "子供", exampleReading: "こども", exampleMeaning: "child" },
  { id: "kj-社", glyph: "社", meaning: "company / shrine", onyomi: "しゃ", kunyomi: "やしろ", level: "N4", example: "会社", exampleReading: "かいしゃ", exampleMeaning: "company" },
  { id: "kj-会", glyph: "会", meaning: "meet / association", onyomi: "かい", kunyomi: "あ", level: "N4", example: "会議", exampleReading: "かいぎ", exampleMeaning: "meeting" },
  { id: "kj-駅", glyph: "駅", meaning: "station", onyomi: "えき", kunyomi: "—", level: "N5", example: "東京駅", exampleReading: "とうきょうえき", exampleMeaning: "Tokyo Station" },
  { id: "kj-店", glyph: "店", meaning: "shop", onyomi: "てん", kunyomi: "みせ", level: "N4", example: "店員", exampleReading: "てんいん", exampleMeaning: "shop clerk" },
  { id: "kj-問", glyph: "問", meaning: "question", onyomi: "もん", kunyomi: "と", level: "N4", example: "問題", exampleReading: "もんだい", exampleMeaning: "problem / question" },
  { id: "kj-題", glyph: "題", meaning: "topic / title", onyomi: "だい", kunyomi: "—", level: "N4", example: "問題", exampleReading: "もんだい", exampleMeaning: "problem" },
  { id: "kj-意", glyph: "意", meaning: "mind / meaning", onyomi: "い", kunyomi: "—", level: "N3", example: "意味", exampleReading: "いみ", exampleMeaning: "meaning" },
  { id: "kj-味", glyph: "味", meaning: "taste / flavor", onyomi: "み", kunyomi: "あじ", level: "N4", example: "意味", exampleReading: "いみ", exampleMeaning: "meaning" },
  { id: "kj-調", glyph: "調", meaning: "investigate / tone", onyomi: "ちょう", kunyomi: "しら", level: "N3", example: "調査", exampleReading: "ちょうさ", exampleMeaning: "survey" },
  { id: "kj-査", glyph: "査", meaning: "inspect", onyomi: "さ", kunyomi: "—", level: "N3", example: "調査", exampleReading: "ちょうさ", exampleMeaning: "investigation" },
  { id: "kj-報", glyph: "報", meaning: "report / reward", onyomi: "ほう", kunyomi: "むく", level: "N3", example: "情報", exampleReading: "じょうほう", exampleMeaning: "information" },
  { id: "kj-情", glyph: "情", meaning: "feeling / facts", onyomi: "じょう", kunyomi: "なさ", level: "N3", example: "情報", exampleReading: "じょうほう", exampleMeaning: "information" },
  { id: "kj-対", glyph: "対", meaning: "versus / opposite", onyomi: "たい", kunyomi: "—", level: "N2", example: "対策", exampleReading: "たいさく", exampleMeaning: "countermeasure" },
  { id: "kj-策", glyph: "策", meaning: "plan / measure", onyomi: "さく", kunyomi: "—", level: "N2", example: "政策", exampleReading: "せいさく", exampleMeaning: "policy" },
  { id: "kj-果", glyph: "果", meaning: "fruit / result", onyomi: "か", kunyomi: "は", level: "N3", example: "結果", exampleReading: "けっか", exampleMeaning: "result" },
  { id: "kj-責", glyph: "責", meaning: "responsibility", onyomi: "せき", kunyomi: "せ", level: "N2", example: "責任", exampleReading: "せきにん", exampleMeaning: "responsibility" },
];
