import type { VocabItem } from "./types";

export const VOCAB: VocabItem[] = [
  { id: "v-こんにちは", jp: "こんにちは", reading: "こんにちは", meaning: "hello (daytime)", level: "N5", pos: "phrase" },
  { id: "v-ありがとう", jp: "ありがとう", reading: "ありがとう", meaning: "thank you", level: "N5", pos: "phrase" },
  { id: "v-すみません", jp: "すみません", reading: "すみません", meaning: "excuse me / sorry", level: "N5", pos: "phrase" },
  { id: "v-お願いします", jp: "お願いします", reading: "おねがいします", meaning: "please (request)", level: "N5", pos: "phrase" },
  { id: "v-食べる", jp: "食べる", reading: "たべる", meaning: "to eat", level: "N5", pos: "verb" },
  { id: "v-飲む", jp: "飲む", reading: "のむ", meaning: "to drink", level: "N5", pos: "verb" },
  { id: "v-行く", jp: "行く", reading: "いく", meaning: "to go", level: "N5", pos: "verb" },
  { id: "v-来る", jp: "来る", reading: "くる", meaning: "to come", level: "N5", pos: "verb" },
  { id: "v-帰る", jp: "帰る", reading: "かえる", meaning: "to return home", level: "N5", pos: "verb" },
  { id: "v-見る", jp: "見る", reading: "みる", meaning: "to see / watch", level: "N5", pos: "verb" },
  { id: "v-聞く", jp: "聞く", reading: "きく", meaning: "to listen / ask", level: "N5", pos: "verb" },
  { id: "v-読む", jp: "読む", reading: "よむ", meaning: "to read", level: "N5", pos: "verb" },
  { id: "v-書く", jp: "書く", reading: "かく", meaning: "to write", level: "N5", pos: "verb" },
  { id: "v-話す", jp: "話す", reading: "はなす", meaning: "to speak", level: "N5", pos: "verb" },
  { id: "v-買う", jp: "買う", reading: "かう", meaning: "to buy", level: "N5", pos: "verb" },
  { id: "v-待つ", jp: "待つ", reading: "まつ", meaning: "to wait", level: "N5", pos: "verb" },
  { id: "v-する", jp: "する", reading: "する", meaning: "to do", level: "N5", pos: "verb" },
  { id: "v-いる", jp: "いる", reading: "いる", meaning: "to exist (animate)", level: "N5", pos: "verb" },
  { id: "v-ある", jp: "ある", reading: "ある", meaning: "to exist (inanimate)", level: "N5", pos: "verb" },
  { id: "v-大きい", jp: "大きい", reading: "おおきい", meaning: "big", level: "N5", pos: "i-adj" },
  { id: "v-小さい", jp: "小さい", reading: "ちいさい", meaning: "small", level: "N5", pos: "i-adj" },
  { id: "v-新しい", jp: "新しい", reading: "あたらしい", meaning: "new", level: "N5", pos: "i-adj" },
  { id: "v-古い", jp: "古い", reading: "ふるい", meaning: "old (not age)", level: "N5", pos: "i-adj" },
  { id: "v-高い", jp: "高い", reading: "たかい", meaning: "expensive / tall", level: "N5", pos: "i-adj" },
  { id: "v-安い", jp: "安い", reading: "やすい", meaning: "cheap", level: "N5", pos: "i-adj" },
  { id: "v-多い", jp: "多い", reading: "おおい", meaning: "many", level: "N5", pos: "i-adj" },
  { id: "v-少ない", jp: "少ない", reading: "すくない", meaning: "few", level: "N5", pos: "i-adj" },
  { id: "v-難しい", jp: "難しい", reading: "むずかしい", meaning: "difficult", level: "N5", pos: "i-adj" },
  { id: "v-易しい", jp: "易しい", reading: "やさしい", meaning: "easy", level: "N5", pos: "i-adj" },
  { id: "v-好き", jp: "好き", reading: "すき", meaning: "liked", level: "N5", pos: "na-adj" },
  { id: "v-今日", jp: "今日", reading: "きょう", meaning: "today", level: "N5", pos: "noun" },
  { id: "v-明日", jp: "明日", reading: "あした", meaning: "tomorrow", level: "N5", pos: "noun" },
  { id: "v-昨日", jp: "昨日", reading: "きのう", meaning: "yesterday", level: "N5", pos: "noun" },
  { id: "v-朝", jp: "朝", reading: "あさ", meaning: "morning", level: "N5", pos: "noun" },
  { id: "v-夜", jp: "夜", reading: "よる", meaning: "night", level: "N5", pos: "noun" },
  { id: "v-友達", jp: "友達", reading: "ともだち", meaning: "friend", level: "N5", pos: "noun" },
  { id: "v-先生", jp: "先生", reading: "せんせい", meaning: "teacher", level: "N5", pos: "noun" },
  { id: "v-学生", jp: "学生", reading: "がくせい", meaning: "student", level: "N5", pos: "noun" },
  { id: "v-電車", jp: "電車", reading: "でんしゃ", meaning: "train", level: "N5", pos: "noun" },
  { id: "v-駅", jp: "駅", reading: "えき", meaning: "station", level: "N5", pos: "noun" },
  { id: "v-仕事", jp: "仕事", reading: "しごと", meaning: "work / job", level: "N4", pos: "noun" },
  { id: "v-経験", jp: "経験", reading: "けいけん", meaning: "experience", level: "N4", pos: "noun" },
  { id: "v-準備", jp: "準備", reading: "じゅんび", meaning: "preparation", level: "N4", pos: "noun" },
  { id: "v-都合", jp: "都合", reading: "つごう", meaning: "convenience / circumstances", level: "N4", pos: "noun" },
  { id: "v-連絡", jp: "連絡", reading: "れんらく", meaning: "contact", level: "N4", pos: "noun" },
  { id: "v-予約", jp: "予約", reading: "よやく", meaning: "reservation", level: "N4", pos: "noun" },
  { id: "v-約束", jp: "約束", reading: "やくそく", meaning: "promise", level: "N4", pos: "noun" },
  { id: "v-案内", jp: "案内", reading: "あんない", meaning: "guidance", level: "N4", pos: "noun" },
  { id: "v-説明", jp: "説明", reading: "せつめい", meaning: "explanation", level: "N4", pos: "noun" },
  { id: "v-必要", jp: "必要", reading: "ひつよう", meaning: "necessary", level: "N4", pos: "na-adj" },
  { id: "v-十分", jp: "十分", reading: "じゅうぶん", meaning: "enough", level: "N4", pos: "na-adj" },
  { id: "v-続ける", jp: "続ける", reading: "つづける", meaning: "to continue", level: "N4", pos: "verb" },
  { id: "v-始める", jp: "始める", reading: "はじめる", meaning: "to begin", level: "N4", pos: "verb" },
  { id: "v-終わる", jp: "終わる", reading: "おわる", meaning: "to end", level: "N4", pos: "verb" },
  { id: "v-決める", jp: "決める", reading: "きめる", meaning: "to decide", level: "N4", pos: "verb" },
  { id: "v-確認", jp: "確認", reading: "かくにん", meaning: "confirmation", level: "N3", pos: "noun" },
  { id: "v-検討", jp: "検討", reading: "けんとう", meaning: "consideration / review", level: "N3", pos: "noun" },
  { id: "v-影響", jp: "影響", reading: "えいきょう", meaning: "influence / effect", level: "N3", pos: "noun" },
  { id: "v-状況", jp: "状況", reading: "じょうきょう", meaning: "situation", level: "N3", pos: "noun" },
  { id: "v-関係", jp: "関係", reading: "かんけい", meaning: "relationship", level: "N3", pos: "noun" },
  { id: "v-意味", jp: "意味", reading: "いみ", meaning: "meaning", level: "N3", pos: "noun" },
  { id: "v-理由", jp: "理由", reading: "りゆう", meaning: "reason", level: "N3", pos: "noun" },
  { id: "v-方法", jp: "方法", reading: "ほうほう", meaning: "method", level: "N3", pos: "noun" },
  { id: "v-機会", jp: "機会", reading: "きかい", meaning: "opportunity", level: "N3", pos: "noun" },
  { id: "v-結果", jp: "結果", reading: "けっか", meaning: "result", level: "N3", pos: "noun" },
  { id: "v-増える", jp: "増える", reading: "ふえる", meaning: "to increase", level: "N3", pos: "verb" },
  { id: "v-減る", jp: "減る", reading: "へる", meaning: "to decrease", level: "N3", pos: "verb" },
  { id: "v-優先", jp: "優先", reading: "ゆうせん", meaning: "priority", level: "N2", pos: "noun" },
  { id: "v-提案", jp: "提案", reading: "ていあん", meaning: "proposal", level: "N2", pos: "noun" },
  { id: "v-達成", jp: "達成", reading: "たっせい", meaning: "achievement", level: "N2", pos: "noun" },
  { id: "v-継続", jp: "継続", reading: "けいぞく", meaning: "continuation", level: "N2", pos: "noun" },
  { id: "v-改善", jp: "改善", reading: "かいぜん", meaning: "improvement", level: "N2", pos: "noun" },
  { id: "v-効率", jp: "効率", reading: "こうりつ", meaning: "efficiency", level: "N2", pos: "noun" },
  { id: "v-傾向", jp: "傾向", reading: "けいこう", meaning: "tendency", level: "N2", pos: "noun" },
  { id: "v-役割", jp: "役割", reading: "やくわり", meaning: "role", level: "N2", pos: "noun" },
  { id: "v-意識", jp: "意識", reading: "いしき", meaning: "awareness", level: "N2", pos: "noun" },
  { id: "v-判断", jp: "判断", reading: "はんだん", meaning: "judgment", level: "N2", pos: "noun" },
  { id: "v-前提", jp: "前提", reading: "ぜんてい", meaning: "premise", level: "N2", pos: "noun" },
  { id: "v-具体的", jp: "具体的", reading: "ぐたいてき", meaning: "concrete / specific", level: "N2", pos: "na-adj" },
  { id: "v-抽象的", jp: "抽象的", reading: "ちゅうしょうてき", meaning: "abstract", level: "N2", pos: "na-adj" },
  { id: "v-水", jp: "水", reading: "みず", meaning: "water", level: "N5", pos: "noun" },
  { id: "v-お茶", jp: "お茶", reading: "おちゃ", meaning: "tea", level: "N5", pos: "noun" },
  { id: "v-ご飯", jp: "ご飯", reading: "ごはん", meaning: "cooked rice / a meal", level: "N5", pos: "noun" },
  { id: "v-映画", jp: "映画", reading: "えいが", meaning: "movie", level: "N5", pos: "noun" },
  { id: "v-音楽", jp: "音楽", reading: "おんがく", meaning: "music", level: "N5", pos: "noun" },
  { id: "v-天気", jp: "天気", reading: "てんき", meaning: "weather", level: "N5", pos: "noun" },
  { id: "v-雨", jp: "雨", reading: "あめ", meaning: "rain", level: "N5", pos: "noun" },
  { id: "v-暑い", jp: "暑い", reading: "あつい", meaning: "hot (weather)", level: "N5", pos: "i-adj" },
  { id: "v-寒い", jp: "寒い", reading: "さむい", meaning: "cold (weather)", level: "N5", pos: "i-adj" },
  { id: "v-忙しい", jp: "忙しい", reading: "いそがしい", meaning: "busy", level: "N5", pos: "i-adj" },
  { id: "v-分かる", jp: "分かる", reading: "わかる", meaning: "to understand", level: "N5", pos: "verb" },
  { id: "v-教える", jp: "教える", reading: "おしえる", meaning: "to teach", level: "N5", pos: "verb" },
  { id: "v-覚える", jp: "覚える", reading: "おぼえる", meaning: "to memorize", level: "N5", pos: "verb" },
  { id: "v-働く", jp: "働く", reading: "はたらく", meaning: "to work", level: "N5", pos: "verb" },
  { id: "v-休む", jp: "休む", reading: "やすむ", meaning: "to rest / be absent", level: "N5", pos: "verb" },
  { id: "v-使う", jp: "使う", reading: "つかう", meaning: "to use", level: "N5", pos: "verb" },
  { id: "v-作る", jp: "作る", reading: "つくる", meaning: "to make", level: "N5", pos: "verb" },
  { id: "v-返事", jp: "返事", reading: "へんじ", meaning: "reply", level: "N4", pos: "noun" },
  { id: "v-相談", jp: "相談", reading: "そうだん", meaning: "consultation", level: "N4", pos: "noun" },
  { id: "v-意見", jp: "意見", reading: "いけん", meaning: "opinion", level: "N4", pos: "noun" },
  { id: "v-成功", jp: "成功", reading: "せいこう", meaning: "success", level: "N4", pos: "noun" },
  { id: "v-失敗", jp: "失敗", reading: "しっぱい", meaning: "failure", level: "N4", pos: "noun" },
  { id: "v-参加", jp: "参加", reading: "さんか", meaning: "participation", level: "N4", pos: "noun" },
  { id: "v-注意", jp: "注意", reading: "ちゅうい", meaning: "caution / attention", level: "N4", pos: "noun" },
  { id: "v-安全", jp: "安全", reading: "あんぜん", meaning: "safety", level: "N4", pos: "na-adj" },
  { id: "v-普通", jp: "普通", reading: "ふつう", meaning: "ordinary / usually", level: "N4", pos: "na-adj" },
  { id: "v-責任", jp: "責任", reading: "せきにん", meaning: "responsibility", level: "N3", pos: "noun" },
  { id: "v-目標", jp: "目標", reading: "もくひょう", meaning: "goal / target", level: "N3", pos: "noun" },
  { id: "v-課題", jp: "課題", reading: "かだい", meaning: "task / issue", level: "N3", pos: "noun" },
  { id: "v-環境", jp: "環境", reading: "かんきょう", meaning: "environment", level: "N3", pos: "noun" },
  { id: "v-社会", jp: "社会", reading: "しゃかい", meaning: "society", level: "N3", pos: "noun" },
  { id: "v-情報", jp: "情報", reading: "じょうほう", meaning: "information", level: "N3", pos: "noun" },
  { id: "v-議論", jp: "議論", reading: "ぎろん", meaning: "debate / discussion", level: "N2", pos: "noun" },
  { id: "v-主張", jp: "主張", reading: "しゅちょう", meaning: "assertion / claim", level: "N2", pos: "noun" },
  { id: "v-指摘", jp: "指摘", reading: "してき", meaning: "pointing out", level: "N2", pos: "noun" },
  { id: "v-対策", jp: "対策", reading: "たいさく", meaning: "countermeasure", level: "N2", pos: "noun" },
  { id: "v-貢献", jp: "貢献", reading: "こうけん", meaning: "contribution", level: "N2", pos: "noun" },
  { id: "v-把握", jp: "把握", reading: "はあく", meaning: "grasp / understanding", level: "N2", pos: "noun" },
];
