/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppPlanRouteImport } from './routes/app/plan'
import { Route as AppPracticeRouteImport } from './routes/app/practice'
import { Route as AppSenseiRouteImport } from './routes/app/sensei'
import { Route as AppStatsRouteImport } from './routes/app/stats'
import { Route as AppTodayRouteImport } from './routes/app/today'
import { Route as AppWriteRouteImport } from './routes/app/write'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppPracticeKindRouteImport } from './routes/app/practice.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSenseiRoute = AppSenseiRouteImport.update({
  id: '/sensei',
  path: '/sensei',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWriteRoute = AppWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPracticeKindRoute = AppPracticeKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => AppPracticeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/app/plan': typeof AppPlanRoute
  '/app/practice': typeof AppPracticeRouteWithChildren
  '/app/sensei': typeof AppSenseiRoute
  '/app/stats': typeof AppStatsRoute
  '/app/today': typeof AppTodayRoute
  '/app/write': typeof AppWriteRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/practice/$kind': typeof AppPracticeKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/app/plan': typeof AppPlanRoute
  '/app/practice': typeof AppPracticeRouteWithChildren
  '/app/sensei': typeof AppSenseiRoute
  '/app/stats': typeof AppStatsRoute
  '/app/today': typeof AppTodayRoute
  '/app/write': typeof AppWriteRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/practice/$kind': typeof AppPracticeKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/app/plan': typeof AppPlanRoute
  '/app/practice': typeof AppPracticeRouteWithChildren
  '/app/sensei': typeof AppSenseiRoute
  '/app/stats': typeof AppStatsRoute
  '/app/today': typeof AppTodayRoute
  '/app/write': typeof AppWriteRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/practice/$kind': typeof AppPracticeKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboard'
    | '/app/plan'
    | '/app/practice'
    | '/app/sensei'
    | '/app/stats'
    | '/app/today'
    | '/app/write'
    | '/app/'
    | '/api/auth/$'
    | '/app/practice/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboard'
    | '/app/plan'
    | '/app/practice'
    | '/app/sensei'
    | '/app/stats'
    | '/app/today'
    | '/app/write'
    | '/app'
    | '/api/auth/$'
    | '/app/practice/$kind'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboard'
    | '/app/plan'
    | '/app/practice'
    | '/app/sensei'
    | '/app/stats'
    | '/app/today'
    | '/app/write'
    | '/app/'
    | '/api/auth/$'
    | '/app/practice/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/practice': {
      id: '/app/practice'
      path: '/practice'
      fullPath: '/app/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sensei': {
      id: '/app/sensei'
      path: '/sensei'
      fullPath: '/app/sensei'
      preLoaderRoute: typeof AppSenseiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/write': {
      id: '/app/write'
      path: '/write'
      fullPath: '/app/write'
      preLoaderRoute: typeof AppWriteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/practice/$kind': {
      id: '/app/practice/$kind'
      path: '/$kind'
      fullPath: '/app/practice/$kind'
      preLoaderRoute: typeof AppPracticeKindRouteImport
      parentRoute: typeof AppPracticeRoute
    }
  }
}

interface AppPracticeRouteChildren {
  AppPracticeKindRoute: typeof AppPracticeKindRoute
}

const AppPracticeRouteChildren: AppPracticeRouteChildren = {
  AppPracticeKindRoute: AppPracticeKindRoute,
}

const AppPracticeRouteWithChildren = AppPracticeRoute._addFileChildren(
  AppPracticeRouteChildren,
)

interface AppRouteRouteChildren {
  AppPlanRoute: typeof AppPlanRoute
  AppPracticeRoute: typeof AppPracticeRouteWithChildren
  AppSenseiRoute: typeof AppSenseiRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppWriteRoute: typeof AppWriteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPlanRoute: AppPlanRoute,
  AppPracticeRoute: AppPracticeRouteWithChildren,
  AppSenseiRoute: AppSenseiRoute,
  AppStatsRoute: AppStatsRoute,
  AppTodayRoute: AppTodayRoute,
  AppWriteRoute: AppWriteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
